export { default as MenClothesIcon } from './men-clothes'
export { default as WomenClothesIcon } from './women-clothes'
export { default as ElectronicIcon } from './electronic'
export { default as JewelIcon } from './jewel'
export { default as HeartIcon } from './heart'
export { default as HomeIcon } from './home'
export { default as FavoritesIcon } from './favorites'
export { default as OrderIcon } from './order'
export { default as ProfileIcon } from './profile'
export * from './star'
