export { default as fontSize } from './fonts'
export { default as spacings } from './spacings'
export { default as fixedValues } from './fixed-values'
export { default as colors } from './colors'
export { default as sizes } from './sizes'
export type Size =
  | 'xxxs'
  | 'xxs'
  | 'xxs2'
  | 'xs'
  | 's'
  | 'm'
  | 'l'
  | 'xl'
  | 'xxl'
  | 'xxl2'
export * from './sizes'
