export { default as appFontSize } from './fonts'
export { default as appSpacings } from './spacings'
export { default as appFixedValues } from './fixed-values'
export { default as appColors } from './colors'
export { default as appSizes } from './sizes'
export type Size =
  | 'xxxs'
  | 'xxs'
  | 'xxs2'
  | 'xs'
  | 's'
  | 'm'
  | 'l'
  | 'xl'
  | 'xxl'
  | 'xxl2'
export * from './sizes'
